#!/usr/bin/env sh
# Copyright 2015 the original author or authors. Apache 2.0 License.

##############################################################################
# Gradle start up script for POSIX generated by: gradle wrapper
##############################################################################
set -e

APP_HOME=$( cd "${0%/*}/.." && pwd -P )
APP_NAME="Gradlew"
APP_BASE_NAME="${0##*/}"

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use JAVA_HOME if set; otherwise locate java
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' found in PATH."
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"

die() {
    echo
    echo "$*"
    echo
    exit 1
}
